x-airflow-common: &airflow-common
  build: .
  env_file:
    - .env
  environment:
    &airflow-common-env
    AIRFLOW__CORE__EXECUTOR: LocalExecutor
    AIRFLOW__CORE__LOAD_EXAMPLES: 'false'
    AIRFLOW__DATABASE__SQL_ALCHEMY_CONN: postgresql+psycopg2://airflow:airflow@postgres/airflow
    AIRFLOW__MLFLOW__TRACKING_URI: ${MLFLOW_TRACKING_URI:-http://mlflow-server:5000}
    MLFLOW_TRACKING_URI: ${MLFLOW_TRACKING_URI:-http://mlflow-server:5000}
    PYTHONPATH: /opt/airflow
  volumes:
    - ./airflow/dags:/opt/airflow/dags:rw
    - ./airflow/logs:/opt/airflow/logs:rw
    - ./airflow/plugins:/opt/airflow/plugins:rw
    - ./src:/opt/airflow/src:ro
    - ./data:/opt/airflow/data:rw
    - ./config:/opt/airflow/config:rw
  user: "${AIRFLOW_UID:-1000}:0"
  depends_on:
    postgres:
      condition: service_healthy
    mlflow-server:
      condition: service_started

networks:
  mlops_network:
    name: mlops_network
    driver: bridge


services:
  postgres:
    image: postgres:13
    container_name: stockpred-postgres
    environment:
      - POSTGRES_USER=airflow
      - POSTGRES_PASSWORD=airflow
      - POSTGRES_DB=airflow
    ports:
      - "5433:5432"
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "airflow"]
      interval: 5s
      timeout: 5s
      retries: 5
    volumes:
      - ./init-multiple-db.sh:/docker-entrypoint-initdb.d/init-multiple-db.sh:ro
      - airflow-db-volume:/var/lib/postgresql/data
    networks:
      - mlops_network

  mlflow-server:
    build: 
     context: .
     dockerfile: ./Dockerfile.mlflow
    container_name: stockpred-mlflow-server
    ports:
      - "5000:5000" #5001:5000
    environment:  
      - POSTGRES_USER=airflow
      - POSTGRES_PASSWORD=airflow
      - POSTGRES_DATABASE=mlflow
      - MLFLOW_TRACKING_URI=postgresql://airflow:airflow@postgres:5432/mlflow
      - MLFLOW_TRACKING_URI=postgresql://airflow:airflow@postgres/mlflow

    command: >
      mlflow server
        --host 0.0.0.0
        --port 5000
        --backend-store-uri postgresql://airflow:airflow@postgres/mlflow
        --default-artifact-root /mlruns
    volumes:
      - airflow-mlflow-volume:/mlruns
    networks:
      - mlops_network
    depends_on:
      postgres:
        condition: service_healthy
    healthcheck:
      test: ["CMD", "curl", "--fail", "http://localhost:5000/health"]
      interval: 10s
      timeout: 5s
      retries: 5

  airflow-webserver:
    <<: *airflow-common
    container_name: stockpred-airflow-webserver
    command: webserver
    ports:
      - "8080:8080"
    healthcheck:
      test: ["CMD", "curl", "--fail", "http://localhost:8080/health"]
      interval: 30s
      timeout: 10s
      retries: 5
    networks:
      - mlops_network

  airflow-scheduler:
    <<: *airflow-common
    container_name: stockpred-airflow-scheduler
    command: scheduler
    ports:
      - "8888:8888"
    healthcheck:
      test: ["CMD-SHELL", "airflow jobs check --job-type SchedulerJob --hostname \"$$HOSTNAME\""]
      interval: 60s
      timeout: 30s
      retries: 5
    networks:
      - mlops_network

  frontend:
    build:
      context: .
      dockerfile: ./Dockerfile.frontend
    container_name: stockpred-frontend
    ports:
      - "8000:80" #"8000:80"
    # deploy:
    #   resources:
    #     reservations:
    #       devices:
    #         - driver: nvidia
    #           count: all
    #           capabilities: [gpu]
    command: uvicorn src.api.main:app --host 0.0.0.0 --port 80 --reload
    volumes:
    #  - ./data:/usr/share/nginx/html/data:ro
      - ./data:/opt/airflow/data:ro # Mount the entire data directory from the host read-only
      - ./src:/opt/airflow/src:ro # Assuming uvicorn runs from /opt/airflow
      # - ./src:/app/src:ro  # Adjusted volume path to match WORKDIR /app
      - ./templates:/opt/airflow/templates:ro # Mount templates read-only
      - ./config:/opt/airflow/config:ro  # Mount config directory read-only
    environment:
      - PYTHONPATH=/opt/airflow
      # - PYTHONPATH=/app
    depends_on:
      - airflow-webserver
    networks:
      - mlops_network

volumes:
  airflow-db-volume:
  airflow-mlflow-volume:

