# Dockerfile.frontend

FROM python:3.11-slim

WORKDIR /app

# Copy toàn bộ mã nguồn frontend
COPY ./frontend /app

# Cài đặt các gói cần thiết
RUN pip install --no-cache-dir fastapi uvicorn jinja2

# Expose port
EXPOSE 8000

CMD ["uvicorn", "main:app", "--host", "0.0.0.0", "--port", "8000"]
