x-airflow-common: &airflow-common
  build: .
  env_file:
    - .env
  environment:
    &airflow-common-env
    AIRFLOW__CORE__EXECUTOR: LocalExecutor
    AIRFLOW__CORE__LOAD_EXAMPLES: 'false'
    AIRFLOW__DATABASE__SQL_ALCHEMY_CONN: postgresql+psycopg2://airflow:airflow@postgres/airflow
    AIRFLOW__MLFLOW__TRACKING_URI: ${MLFLOW_TRACKING_URI:-http://mlflow-server:5000}
    MLFLOW_TRACKING_URI: ${MLFLOW_TRACKING_URI:-http://mlflow-server:5000}
    PYTHONPATH: /opt/airflow
  volumes:
    - ./airflow/dags:/opt/airflow/dags:rw
    - ./airflow/logs:/opt/airflow/logs:rw
    - ./airflow/plugins:/opt/airflow/plugins:rw
    - ./src:/opt/airflow/src:ro
    - ./data:/opt/airflow/data:rw
    - ./config:/opt/airflow/config:rw
  user: "${AIRFLOW_UID:-1000}:0"
  depends_on:
    postgres:
      condition: service_healthy
    mlflow-server:
      condition: service_started

services:
  postgres:
    image: postgres:13
    container_name: stockpred-postgres
    environment:
      - POSTGRES_USER=airflow
      - POSTGRES_PASSWORD=airflow
      - POSTGRES_DB=airflow
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "airflow"]
      interval: 5s
      timeout: 5s
      retries: 5
    volumes:
      - airflow-db-volume:/var/lib/postgresql/data

  mlflow-server:
    image: ghcr.io/mlflow/mlflow:v2.13.1
    container_name: stockpred-mlflow-server
    ports:
      - "5001:5000"
    command: >
      mlflow server
        --host 0.0.0.0
        --port 5000
        --backend-store-uri /mlruns
    volumes:
      - airflow-mlflow-volume:/mlruns

  airflow-webserver:
    <<: *airflow-common
    container_name: stockpred-airflow-webserver
    command: webserver
    ports:
      - "8080:8080"
    healthcheck:
      test: ["CMD", "curl", "--fail", "http://localhost:8080/health"]
      interval: 30s
      timeout: 10s
      retries: 5

  airflow-scheduler:
    <<: *airflow-common
    container_name: stockpred-airflow-scheduler
    command: scheduler
    ports:
      - "8888:8888"
    healthcheck:
      test: ["CMD-SHELL", "airflow jobs check --job-type SchedulerJob --hostname \"$$HOSTNAME\""]
      interval: 60s
      timeout: 30s
      retries: 5

  frontend:
    build:
      context: .
      dockerfile: ./Dockerfile.frontend
    container_name: stockpred-frontend
    ports:
      - "8000:8000" #"8000:80"
    command: uvicorn src.api.main:app --host 0.0.0.0 --port 8000 --reload 
    volumes:
    #  - ./data:/usr/share/nginx/html/data:ro
      - ./data:/opt/airflow/data:ro # Mount the entire data directory from the host read-only
      - ./src:/opt/airflow/src:ro # Assuming uvicorn runs from /opt/airflow
      - ./templates:/opt/airflow/templates:ro # Mount templates read-only
      - ./config:/opt/airflow/config:ro  # Mount config directory read-only
    environment:
      - PYTHONPATH=/opt/airflow
    depends_on:
      - airflow-webserver

volumes:
  airflow-db-volume:
  airflow-mlflow-volume:
