FROM ghcr.io/mlflow/mlflow:v2.13.1

# Install required packages
RUN pip install psycopg2-binary

# Set working directory
WORKDIR /mlflow

# Keep container running
CMD ["mlflow", "server", "--host", "0.0.0.0"]